version: '3.5'

services:
  postgres:
    container_name: "postgres_db"
    image: postgres
    environment:
      POSTGRES_USER: matheus
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres_db
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
